server:
  port: 0

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/online-shop-realm
  liquibase:
    enabled: true
  application:
    name: user-service
  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: validate
  datasource:
    driverClassName: org.postgresql.Driver
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres