server:
  port: 0

spring:
  liquibase:
    enabled: true
  application:
    name: user-service
  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: none
  datasource:
    driverClassName: org.postgresql.Driver
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres